# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ba0b5604d6e7170e6b2ca40e2a5803c0fee55f07970f8db82750b591fb5373cb5d4f3d4720fbed6ba829ddcb6848e9a88956adbc38318d8bef2bd48dcdad7e3

test:
  secret_key_base: 77c66f70f8ef1244f7feca02ad05bb56925b7051340073bc4879a3eac878af23848d2058ca98fff3baabfa08e1458f32849226104d856737be7fe6cb0fb70f6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
